### ISSUE TITLE
Rust drivers for SPS30-uart

### ISSUE THREAD

**Issue by iohe** [Sensirion/info#1]
Hi Team,
    Would like to add two RUST drivers for SPS30 (uart) in section named "Third party repositories provided by our developer community"
   https://crates.io/crates/sensirion-hdlc  with corresponding github repo: https://github.com/iohe/sensirion-hdlc
   and 
    https://crates.io/crates/sps30  (uart driver) with corresponding github repo: https://github.com/iohe/sps30
Thank you

**Comment by psachs** [comment]
Hi

Thank you very much for your request. I assigned it to the responsible people. Due to holiday absences it might take until next week until the drivers are added.

We are very happy to have more rust drivers available for our sensors and are happy to test them and add them to our third party repository section.

Best regards,
Pascal

**Comment by winkj** [comment]
Thanks for the submission. I added this, please let me know if you'd recommend changes to the wording
